# Generated by Django 5.2.4 on 2025-08-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='someone@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='john doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='resume', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
